# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{text_to_epub}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jason LaPier"]
  s.date = %q{2010-12-04}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{jason.lapier@gmail.com}
  s.executables = ["new_book.rb", "gen_epub.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/gen_epub.rb",
    "bin/new_book.rb",
    "config_sample.yml",
    "lib/book.rb",
    "lib/chapter.rb",
    "lib/epub_setup.rb",
    "lib/text_to_epub.rb",
    "spec/book_spec.rb",
    "spec/chapter_spec.rb",
    "spec/epub_setup_spec.rb",
    "spec/spec_helper.rb",
    "templates/META-INF/container.xml",
    "templates/OEBPS/chapter.html.liquid",
    "templates/OEBPS/content.opf.liquid",
    "templates/OEBPS/end_of_book.html.liquid",
    "templates/OEBPS/fonts.css",
    "templates/OEBPS/fonts/BergamoStd-Bold.otf",
    "templates/OEBPS/fonts/BergamoStd-BoldItalic.otf",
    "templates/OEBPS/fonts/BergamoStd-Italic.otf",
    "templates/OEBPS/fonts/BergamoStd-Regular.otf",
    "templates/OEBPS/fonts/OFLGoudyStM-Italic.otf",
    "templates/OEBPS/fonts/OFLGoudyStM.otf",
    "templates/OEBPS/fonts/licenses.txt",
    "templates/OEBPS/fonts/texgyrepagella-bold.otf",
    "templates/OEBPS/fonts/texgyrepagella-bolditalic.otf",
    "templates/OEBPS/fonts/texgyrepagella-italic.otf",
    "templates/OEBPS/fonts/texgyrepagella-regular.otf",
    "templates/OEBPS/fonts/texgyretermes-bold.otf",
    "templates/OEBPS/fonts/texgyretermes-bolditalic.otf",
    "templates/OEBPS/fonts/texgyretermes-italic.otf",
    "templates/OEBPS/fonts/texgyretermes-regular.otf",
    "templates/OEBPS/images/made_by_obf.jpg",
    "templates/OEBPS/print.css",
    "templates/OEBPS/stylesheet.css",
    "templates/OEBPS/title.html.liquid",
    "templates/OEBPS/toc.ncx.liquid",
    "templates/mimetype"
  ]
  s.homepage = %q{http://github.com/jlapier/text_to_epub}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/book_spec.rb",
    "spec/chapter_spec.rb",
    "spec/epub_setup_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<liquid>, [">= 0"])
      s.add_runtime_dependency(%q<uuid>, [">= 0"])
      s.add_runtime_dependency(%q<linguistics>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.2.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<liquid>, [">= 0"])
      s.add_runtime_dependency(%q<uuid>, [">= 0"])
      s.add_runtime_dependency(%q<linguistics>, [">= 0"])
    else
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<liquid>, [">= 0"])
      s.add_dependency(%q<uuid>, [">= 0"])
      s.add_dependency(%q<linguistics>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.2.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<liquid>, [">= 0"])
      s.add_dependency(%q<uuid>, [">= 0"])
      s.add_dependency(%q<linguistics>, [">= 0"])
    end
  else
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<liquid>, [">= 0"])
    s.add_dependency(%q<uuid>, [">= 0"])
    s.add_dependency(%q<linguistics>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.2.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<liquid>, [">= 0"])
    s.add_dependency(%q<uuid>, [">= 0"])
    s.add_dependency(%q<linguistics>, [">= 0"])
  end
end

